### ISSUE TITLE
hawk/dove: include the other risk attitude endpoint (always hawk)

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/simulating-risk#49]
[ADDED 11/8]

[MAYBE we just want to change the logic to play HAWK when dove-neighbors >= r, rather than when dove-neighbors > r, and have the scale go from 0 to 9? I.e., just shift everything over by 1, and include the other endpoint as 0 rather than -1?]

[This might require changing some of the categories? One thing we could do is change the payoffs back to 0/1/2/3 and not have a true expected utility, and then the bottom 3 are risk-inclined, the middle 4 are moderate, and the top 3 are risk-seeking; or the bottom 4, middle 2, top 4–see which gets us more variation in the end states. Or leave the payoffs how they are and do bottom 4 / middle 3 / top 3. Too bad, though–9 categories cleanly separated into 3 “bands”...]

Maybe we need to talk about what to do here?

**Comment by rlskoeser** [comment]
- easier to shift everything so we still start with 0
- revert to original payoffs; two in middle are both EU but different way of breaking ties
- categories will be 012, 3456, 789

dev changes:
- [ ] increase range of risk attitudes
- [ ] change comparison to be `>=` 
- [ ] change payoff back to 2 instead of 2.1
- [ ] update category with new grouping
- [ ] update any readme / documentation
